### ISSUE TITLE
Points disappear after zoom change

### ISSUE THREAD

**Issue by ArvindShantharam** [CI-CMG/deep-sea-corals-exb#10]
Not sure why but I am finding that using the search box to look for a particular species the points will disappear after I zoom out. I wait for the app to redraw everything but only the layers re-draw.  Zooming in brings them back. Using an edge browser on a Win10 machine if that matters

**Comment by jccartwright** [comment]
It sounds like the app is working as designed. Given the large number of points, there is a scale dependency in the web map which only displays the individual points at large scales regardless of the attribute filters that are applied. You should however see the hexbins at the smaller scales and they will adjust color and visibility based on the current filters.

I'm happy to do a screenshare to discuss this interactively if you'd prefer

**Comment by RobertMcGuinn** [comment]
Closed because it's working as designed.
