### ISSUE TITLE
new feature: Search within the 'Synonyms' field and the 'VerbatimScientificName' field.

### ISSUE THREAD

**Issue by RobertMcGuinn** [CI-CMG/deep-sea-corals-exb#19]
origin: Savannah Goode

**Comment by jccartwright** [comment]
Synonyms and VerbatimScientificName are not currently included in the Feature Layer. They can be be added but doing so will likely have a substantial performance impact due the large increase in dataset size. Let's discuss

**Comment by jccartwright** [comment]
added to next release
