### ISSUE TITLE
bug: discrepancies in the record counts 

### ISSUE THREAD

**Issue by RobertMcGuinn** [CI-CMG/deep-sea-corals-exb#21]
The top left
![image](https://github.com/CI-CMG/deep-sea-corals-exb/assets/50679657/1f5c8516-5595-4d2c-bb67-ffbd0b5be8af)
 record counting widget does not always match the one the details pane. 

![image](https://github.com/CI-CMG/deep-sea-corals-exb/assets/50679657/90a5ed41-e8a1-41aa-95ca-9e8b64417d8d)

**Comment by jccartwright** [comment]
removed the record count widget, so issue no longer relevant
