### ISSUE TITLE
new feature: Add AphiaID and link next to species name in details pane

### ISSUE THREAD

**Issue by RobertMcGuinn** [CI-CMG/deep-sea-corals-exb#31]
notes: 

- URL is constructed like this where '135093' is the AphiaID in this example

https://www.marinespecies.org/aphia.php?p=taxdetails&id=135093

**Comment by RobertMcGuinn** [comment]
![image](https://github.com/CI-CMG/deep-sea-corals-exb/assets/50679657/80587960-2e97-40c6-9e3f-caa05d9d54e1)

**Comment by jccartwright** [comment]
AphiaID is not currently one of the fields included in the hosted Feature Layer and therefore not available to the map popup. We can re-create the hosted feature layer to include this additional field but it is not an inconsequential amount of effort. Let's discuss
