### ISSUE TITLE
Model layers not displaying

### ISSUE THREAD

**Issue by jccartwright** [CI-CMG/deep-sea-corals-exb#4]
hides the hexbins but no model layers show

**Comment by RobertMcGuinn** [comment]
I can get the model issues to display.  I think it is just confusing how that part of the interface works.

**Comment by RobertMcGuinn** [comment]
We should look at this together at today's meeting

**Comment by jccartwright** [comment]
appears the issue was that the group layers in the web map had been changed to hidden. The model layers need to have visibility off but any group layer containing one or more layers (or groups) needs to have visibility turned on.
