### ISSUE TITLE
Issue with ObservationDate

### ISSUE THREAD

**Issue by RobertMcGuinn** [CI-CMG/deep-sea-corals-exb#47]
from Tom Hourigan on 20241031: 

Today, I also noticed a quirk in the new portal display.
The ObservationDate in the right hand pop-up has times that seem random. e.g., Catalog# 619559 the pop-up Observation date = 1

1/27/1964, 7:00 PM, but the record's ObservationTime is "NA"

Obviously not a "biggie" but thought I would pass it on,

**Comment by jccartwright** [comment]
ArcGIS is treating these as actual datetime fields and automatically converting the timezone to the local machine. So in the above example w/o a time, it's probably converting to 1/28/1964 00:00 UTC and then adjusting to the local timezone (-5).

We can force these fields to plain text but I think a better option is to convert to UTC and truncate the time in the popup (i.e. details panel). I can demonstrate this to you tomorrow

**Comment by jccartwright** [comment]
Given that the field may contain year, year and month, or year/month/day, only practical option is to treat as string field. Modified in the next release
