### ISSUE TITLE
hexbin summary mismatch

### ISSUE THREAD

**Issue by RobertMcGuinn** [CI-CMG/deep-sea-corals-exb#52]
​John and David,

I was looking at the portal [GitHub Dev version 3.2.0](https://ci-cmg.github.io/deep-sea-corals-exb/) and I saw this hexbin summary that did not make sense.  The summary tab says this hexbin has fish when it does not in reality.  It also says there are 167 records (samples) and 1000 unique ScientificName.  Not sure where this is arising.  I'm assuming something to do with the H3 ID assignment?  The hexbin in question is: 844598bffffffff.  I have not checked the production version yet.  I will record this in our

![image](https://github.com/user-attachments/assets/1687a174-994c-488f-b8b2-b81557a0bfd9)

**Comment by RobertMcGuinn** [comment]
NOTE: I can confirm this does also not occur on the [NCEI test version]https://www.test.ncei.noaa.gov/maps/deep-sea-corals-portal/ at version 3.1.0

**Comment by RobertMcGuinn** [comment]
I can confirm that this only happens when the photo filter is turned on.

**Comment by jccartwright** [comment]
modified the h3-layer widget to group query clauses. When multi-element clauses, e.g. photo filter, were active the SQL was not being properly constructed to query the feature service
