### ISSUE TITLE
We now include Phylum = Chordata (for our purposes...fish)

### ISSUE THREAD

**Issue by RobertMcGuinn** [CI-CMG/deep-sea-corals-exb#6]
'fish' is now a new valid value in 'VernacularNameCategory' as of data dictionary version 20230403-1 : https://docs.google.com/spreadsheets/d/1YDskzxY8OF-34Q8aI04tZvlRbhGZqBSysuie39kYHoI/edit?usp=sharing

You will notice fish data appearing in version 20230828-0 of the database.  

This will need new symbology in the service.  Black squares will do.

**Comment by RobertMcGuinn** [comment]
This will impact pie chart design in the summary window as well.

**Comment by jccartwright** [comment]
added to legend in web map
