### ISSUE TITLE
download issue: when just using the filter Ocean = X, then push download button

### ISSUE THREAD

**Issue by RobertMcGuinn** [CI-CMG/deep-sea-corals-exb#9]
![image](https://github.com/CI-CMG/deep-sea-corals-exb/assets/50679657/0e9bdfe1-217c-450d-af6c-a180f38d47d1)

**Comment by RobertMcGuinn** [comment]
antemeridian issue I assume

**Comment by jccartwright** [comment]
probably. The error message explicitly mentions the antimeridian when the current view crosses it. Would you like to discuss this further?

**Comment by RobertMcGuinn** [comment]
closing: this is fine the way it is.
